version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always

  db:
    image: postgres:14
    container_name: d247-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: d247
    volumes:
      - d247-db-data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      gunicorn backend.wsgi:application --bind 0.0.0.0:5001
    # Keep entrypoint (runs migrate + collectstatic)
    entrypoint: ["/bin/sh", "/code/entrypoint.sh"]

  celery:
    build: .
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info --pool=solo
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    entrypoint: []

  beat:
    build: .
    container_name: celery_beat
    command: celery -A backend beat --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    entrypoint: []

volumes:
  d247-db-data:
